# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11wkuE6Es1NLRMrKAnoZ_Lb4fioXjlgZa
"""

def KT(arr):
    count =0
    for i in arr:
        if(i<2):
            count=count+1
        else:
            for j in range (2,i-1):
                if(i%j==0 and j<i):
                    count= count+1
                    break
    return len(arr)-count
a= [1,5,6,7,11]
print(KT(a))

def Songuyento(n): #Ham kiem tra so nt
    if(n<2):
        return False
    i=2;
    while i <= n/2:
        if(n%i == 0):
            return False
        i+=1
    return True
a=[1,4,6,7,8,11,13]  # Khai bao mot list a
print('\n List A: ')
for i in a:
    print (i, end=" ")
print("\n")
print('{:-^30}'.format("KET QUA LOC SO NT"))
# Doan tren chi de in ra cho dep thoi ^^
for i in a:
    if(Songuyento(i)): # Goi toi ham kiem tra
        print(i, end= " ")

val = float(input('Enter number: ')) 
print(val)
print(type(val))

def laSoNguyenTo(n):
    if (n < 2):
        return False
    elif (n == 2):
        return True
    elif (n % 2 == 0):
        return False
    else:
        # Lặp qua các số lẻ nên bắt đầu từ 3 với bước nhảy là 2
        for i in range(3, n, 2):
            if (n % i == 0):
                return False
    return True

def tongSoNguyenTo(a):
    sum = 0
    for n in a:
        if laSoNguyenTo(n):
            sum += n
    return sum


a = [1, 5, 9, 11]
sum = tongSoNguyenTo(a)
print(sum)

n = float(input("Moi nhap real_number: "))
m = float(input("Moi nhap image_number: "))
class Sothuc :
    def __init__(self,real_number) :
        self.real_number = real_number
    def gttd(self) :
        return (self.real_number *2) * 0.5

class Sophuc(Sothuc) :
    def __init__(self,real_number, image_number) :
        super().__init__(real_number)
        self.image_number = image_number
    def module(self) :
        return (self.image_number**2 + self.real_number**2) ** 0.5

sothuc = Sothuc(n)
print("Tri tuyet doi co gia tri la: ",sothuc.gttd())

sophuc = Sophuc(n,m)
print("module cua so phuc la: ",sophuc.module())